import { useMemo } from 'react';
import { 
  Box, 
  Button, 
  Paper, 
  Typography, 
  Stack, 
  Divider,
  List,
  ListItem,
  ListItemButton,
  ListItemText
} from '@mui/material';
import { 
  Download as DownloadIcon,
  ContentCopy as CopyIcon,
  Print as PrintIcon,
  Article as DocIcon
} from '@mui/icons-material';
import ReactMarkdown from 'react-markdown';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import { useDesignStore } from '../../store/useDesignStore';

export const FinalReportView = () => {
  const { designState } = useDesignStore();

  const sections = useMemo(() => [
    { id: 'reqs', title: '1. Process Requirements', content: designState.process_requirements },
    { id: 'concept', title: '2. Selected Concept', content: `**${designState.selected_concept?.name}**\n\n${designState.selected_concept?.description}` },
    { id: 'basis', title: '3. Detailed Design Basis', content: designState.selected_concept_details },
    { id: 'pfd', title: '4. Flowsheet Description', content: designState.flowsheet_description },
    { id: 'safety', title: '5. Safety Assessment', content: designState.safety_report },
    { id: 'approval', title: '6. Executive Approval Memo', content: designState.project_manager_report },
  ], [designState]);

  const fullReport = useMemo(() => {
      return sections.map(s => `# ${s.title}\n\n${s.content}\n\n---`).join('\n\n');
  }, [sections]);

  const handleCopy = () => {
      navigator.clipboard.writeText(fullReport);
      alert("Report copied to clipboard!");
  };

  const handleDownload = () => {
      const blob = new Blob([fullReport], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `Design_Report_${new Date().toISOString().slice(0,10)}.md`;
      a.click();
  };

  const scrollToSection = (id: string) => {
      const element = document.getElementById(id);
      if (element) element.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <Box sx={{ height: '100%', display: 'flex', gap: 3 }}>
      {/* Navigation Sidebar */}
      <Paper sx={{ width: 280, p: 2, display: { xs: 'none', md: 'flex' }, flexDirection: 'column', bgcolor: 'action.hover' }}>
          <Typography variant="subtitle2" gutterBottom color="primary" sx={{ px: 1 }}>Table of Contents</Typography>
          <List dense>
              {sections.map(s => (
                  <ListItem key={s.id} disablePadding>
                      <ListItemButton onClick={() => scrollToSection(s.id)}>
                          <ListItemText primary={s.title} primaryTypographyProps={{ variant: 'caption', fontWeight: 'medium' }} />
                      </ListItemButton>
                  </ListItem>
              ))}
          </List>
          <Box sx={{ flexGrow: 1 }} />
          <Divider sx={{ my: 2 }} />
          <Stack spacing={1}>
              <Button startIcon={<CopyIcon />} size="small" variant="outlined" onClick={handleCopy}>Copy MD</Button>
              <Button startIcon={<DownloadIcon />} size="small" variant="contained" onClick={handleDownload}>Download .md</Button>
          </Stack>
      </Paper>

      {/* Report Content */}
      <Paper sx={{ 
          flexGrow: 1, 
          p: 6, 
          overflow: 'auto', 
          bgcolor: 'background.paper',
          color: 'text.primary',
          boxShadow: 3
      }}>
          <Box sx={{ maxWidth: 800, mx: 'auto' }}>
              <Box sx={{ mb: 6, textAlign: 'center' }}>
                  <DocIcon sx={{ fontSize: 60, color: 'primary.main', mb: 2 }} />
                  <Typography variant="h3" fontWeight="bold" gutterBottom>Process Design Dossier</Typography>
                  <Typography variant="subtitle1" color="text.secondary">
                      {designState.problem_statement?.slice(0, 100)}...
                  </Typography>
                  <Typography variant="caption" sx={{ mt: 2, display: 'block', opacity: 0.5 }}>
                      Generated by Process Design Agents | {new Date().toLocaleDateString()}
                  </Typography>
              </Box>

              {sections.map(s => (
                  <Box key={s.id} id={s.id} sx={{ 
                      mb: 8,
                      '& h1': { color: 'primary.main', borderBottom: '2px solid', borderColor: 'primary.main', pb: 1, mt: 6, mb: 3 },
                      '& h2': { mt: 4, mb: 2, color: 'secondary.main' },
                      '& table': { width: '100%', borderCollapse: 'collapse', mb: 3, fontSize: '0.9rem' },
                      '& th, & td': { border: '1px solid', borderColor: 'divider', p: 1.5, textAlign: 'left' },
                      '& th': { bgcolor: 'action.hover' },
                      '& p': { lineHeight: 1.8, mb: 2 },
                      '& li': { mb: 1 }
                  }}>
                      <ReactMarkdown remarkPlugins={[remarkGfm, remarkMath]} rehypePlugins={[rehypeKatex]}>
                          {`# ${s.title}\n\n${s.content || "*Section incomplete*"}`}
                      </ReactMarkdown>
                  </Box>
              ))}
          </Box>
      </Paper>
    </Box>
  );
};
