"""add_is_active_to_revision_history

Revision ID: 07815bc9e262
Revises: 7f7276ddb908
Create Date: 2026-01-15 08:06:53.257014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07815bc9e262'
down_revision: Union[str, None] = '7f7276ddb908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revision_history', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revision_history', 'is_active')
    # ### end Alembic commands ###
