"""your_message

Revision ID: 443cfbcd5d71
Revises: 202512171000
Create Date: 2025-12-17 22:50:10.430819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443cfbcd5d71'
down_revision: Union[str, None] = '202512171000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_comments_updated_by'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['updated_by'], ['id'])
    op.drop_index(op.f('ix_project_notes_psv'), table_name='project_notes')
    op.drop_index(op.f('ix_revision_history_entity'), table_name='revision_history')
    op.drop_constraint(op.f('uq_revision_entity_code'), 'revision_history', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_revision_entity_code'), 'revision_history', ['entity_type', 'entity_id', 'revision_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_revision_history_entity'), 'revision_history', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_project_notes_psv'), 'project_notes', ['protective_system_id'], unique=False)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_comments_updated_by'), 'comments', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
