"""add_is_active_to_psv_entities

Revision ID: 7f7276ddb908
Revises: 202601010001
Create Date: 2026-01-15 07:37:09.781011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f7276ddb908'
down_revision: Union[str, None] = '202601010001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.add_column('comments', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('equipment', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('overpressure_scenarios', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('project_notes', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('sizing_cases', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('todos', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'is_active')
    op.drop_column('sizing_cases', 'is_active')
    op.drop_column('project_notes', 'is_active')
    op.drop_column('overpressure_scenarios', 'is_active')
    op.drop_column('equipment', 'is_active')
    op.drop_column('comments', 'is_active')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    # ### end Alembic commands ###
