"""initial_schema

Revision ID: c9328701cffb
Revises: 
Create Date: 2025-12-12 03:11:30.433756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9328701cffb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('engineer', 'lead', 'approver', 'division_manager', 'admin', 'viewer', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='user_status'), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('credentials',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('customers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='customer_status'), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='plant_status'), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('units',
    sa.Column('plant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='unit_status'), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('areas',
    sa.Column('unit_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='area_status'), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('area_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.Enum('vessel', 'tank', 'heat_exchanger', 'column', 'reactor', 'pump', 'compressor', 'piping', 'other', name='equipment_type'), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('design_pressure', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mawp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('design_temp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='equipment_status'), nullable=False),
    sa.Column('location_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_tag'), 'equipment', ['tag'], unique=False)
    op.create_table('projects',
    sa.Column('area_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('phase', sa.Enum('design', 'construction', 'commissioning', 'operation', name='project_phase'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_review', 'checked', 'approved', 'issued', name='project_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('lead_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protective_systems',
    sa.Column('area_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('psv', 'rupture_disc', 'breather_valve', 'flame_arrestor', 'tank_vent', 'control_valve', 'vent_system', 'prv', name='protective_system_type'), nullable=False),
    sa.Column('design_code', sa.Enum('API-520', 'API-521', 'API-2000', 'ASME-VIII', name='design_code'), nullable=False),
    sa.Column('service_fluid', sa.String(length=255), nullable=True),
    sa.Column('fluid_phase', sa.Enum('gas', 'liquid', 'steam', 'two_phase', name='fluid_phase'), nullable=False),
    sa.Column('set_pressure', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mawp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_review', 'checked', 'approved', 'issued', name='psv_status'), nullable=False),
    sa.Column('valve_type', sa.Enum('conventional', 'balanced_bellows', 'pilot_operated', name='valve_operating_type'), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('project_tags', postgresql.ARRAY(sa.UUID(as_uuid=False)), nullable=True),
    sa.Column('inlet_network', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outlet_network', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protective_systems_tag'), 'protective_systems', ['tag'], unique=False)
    op.create_table('attachments',
    sa.Column('protective_system_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('file_uri', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['protective_system_id'], ['protective_systems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('protective_system_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['protective_system_id'], ['protective_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overpressure_scenarios',
    sa.Column('protective_system_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('cause', sa.Enum('blocked_outlet', 'fire_case', 'external_fire', 'tube_rupture', 'thermal_expansion', 'utility_failure', 'control_valve_failure', 'power_failure', 'cooling_water_failure', 'check_valve_failure', 'other', name='scenario_cause'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('relieving_temp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('relieving_pressure', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('phase', sa.Enum('gas', 'liquid', 'steam', 'two_phase', name='scenario_phase'), nullable=False),
    sa.Column('relieving_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('accumulation_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('required_capacity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('assumptions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('code_refs', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_governing', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['protective_system_id'], ['protective_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todos',
    sa.Column('protective_system_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('assigned_to', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['protective_system_id'], ['protective_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_links',
    sa.Column('protective_system_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('equipment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('scenario_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('relationship_type', sa.Enum('protects', 'inlet_from', 'discharge_to', name='equipment_relationship'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protective_system_id'], ['protective_systems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['overpressure_scenarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sizing_cases',
    sa.Column('protective_system_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scenario_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('standard', sa.Enum('API-520', 'API-521', 'API-2000', 'ASME-VIII', 'ISO-4126', name='sizing_standard'), nullable=False),
    sa.Column('method', sa.Enum('gas', 'liquid', 'steam', 'two_phase', name='sizing_method'), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'calculated', 'verified', 'approved', name='sizing_status'), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('approved_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['protective_system_id'], ['protective_systems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['overpressure_scenarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sizing_cases')
    op.drop_table('equipment_links')
    op.drop_table('todos')
    op.drop_table('overpressure_scenarios')
    op.drop_table('comments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_protective_systems_tag'), table_name='protective_systems')
    op.drop_table('protective_systems')
    op.drop_table('projects')
    op.drop_index(op.f('ix_equipment_tag'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_table('areas')
    op.drop_table('units')
    op.drop_table('plants')
    op.drop_table('customers')
    op.drop_table('credentials')
    op.drop_table('users')
    # ### end Alembic commands ###
