"""add_protective_system_projects_table

Revision ID: 202412150001
Revises: 202412120001
Create Date: 2025-12-12 03:33:31.600628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202412150001'
down_revision: Union[str, None] = '202412120001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protective_system_projects',
    sa.Column('protective_system_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protective_system_id'], ['protective_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('protective_system_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protective_system_projects')
    # ### end Alembic commands ###
